### ISSUE TITLE
Project activity & A matrix striping questions

### ISSUE THREAD

**Issue by bgrieder** [lwe-frodo/lwe-frodo#2]
Hello,

I am rewriting (most of) this work in Go to carry out testing and potentially integrating it into a larger platform. I have a few questions.

Project activity
----------

<s>There has not been any commit activity recently (2 years on the code itself). Why is this ? Do you consider the code stable, or has the project moved somewhere else, or ... ?</s>
Is [this project](https://github.com/open-quantum-safe/liboqs/) the reference code now ?

A-Matrix generation
--------
I would like my code to generate matrices which are "compatible" with the C implementation.

<s>1. Is there any reason why this form of striping has been selected in the first place (alternatively to, say, simply setting the uint16 value of the cell with its index number)?</s> This is explained at the bottom of section 6 of the paper

2. When encrypting the striped A matrix using AES-128, the bytes are taken "as is" to be fed into the AES cipher block. However a note above the code mentions that "i and j are written out in the little-endian order". Unless I am missing something, this will only be true if the system is little-endian. Can you please clarify ?

Many Thanks
b.

**Comment by dstebila** [comment]
Hi Bruno,

At this point I would consider the lwe-frodo project code to be archival.  The original Frodo team joined with a few others to create a new version called "FrodoKEM", building on this Frodo, that we submitted to the NIST competition last November.  I would focus on that one.  You can find it at https://frodokem.org/ and https://github.com/Microsoft/PQCrypto-LWEKE.

Douglas

**Comment by bgrieder** [comment]
Thank you
